# Generated by Django 5.1.3 on 2024-11-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battleship", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_turn",
            field=models.BooleanField(default=False),
        ),
    ]
