name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v4
    
    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Build and Test
      working-directory: 214/labs/lab9
      run: |
        mkdir -p build
        cd build
        cmake ..
        cmake --build .
        ctest --output-on-failure
        ./TestSuite
